Create Button.py
xmanu91/Trophees-NSI pull request #3
Opened 2024-12-21 19:59 UTC by malo-0

```python
import pygame

class Button(pygame.sprite.Sprite): 
    def __init__(self, default_color,hover_color, width, height, x, y, image, action):

        self.default_color = default_color  #couleur de base du bouton
        self.hover_color = hover_color  #couleur quand on passe le curseur sur le bouton
        self.width = width #largeur du bouton
        self.height = height #hauteur du bouton
        self.image = pygame.image.load("image.png").convert_alpha() #On load une image
        self.rect = self.image.get_rect(topleft=(x, y))  #Pour placer l'image, on place son point en haut à gauche avec x y 
        self.action = action #on instancira un fonction pour chaque bouton 
        self.alpha = 128  #définie une transparence de 50%, la valeur changera, on verra comment ça rend !

    def update(self): #la fonction qui sera mise à jour en bouclle à chaque frame
        pos = pygame.mouse.get_pos() #prend la position du curseur
        mouse_pressed = pygame.mouse.get_pressed()[0] # vérifie si le bouton gauche de la souris est pressé

        if self.rect.collidepoint(pos):  # s'execute si le curseur touche un bouton
            self.image.fill(self.hover_color) # met de la couleur sur le bouton quand on passe dessus avec le curseur
            self.image.set_alpha(self.alpha) # ajoute de la transparence ppour toujours voir l'image

            if mouse_pressed :  # s'execute si le bouton gauche de la souris est pressé
                self.image.fill((255,0,0)) # rend le bouton rouge
                self.image.set_alpha(self.alpha) # set la transparence
                pygame.Surface.convert_alpha(self.image) # ajoute la transparence

                if self.action: #s'execute si il y a une action instancier au bouton en question (je l'ai mis apart pour prévenir des potentiels bugs)
                    self.action() # execute donc l'action

        else :  #s'execute si le curseur ne touche pas/plus le bouton
            self.image.fill(self.default_color) # on met sa couleur par défaut 
            self.image.set_alpha(self.alpha) # set la transparence
            pygame.Surface.convert_alpha(self.image)  # ajoute la transparence 

```

2024-12-21 22:48 UTC, xmanu91 requested changes
Voilà quelques modifications à faire, merci beaucoup d'avoir été aussi rapide !

2024-12-21 22:48 UTC, xmanu91 commented on ui/Button.py
> +            self.image.set_alpha(self.alpha) # ajoute de la transparence ppour toujours voir l'image
Finalement abandonne l'alpha et fair comme tu avais fait avant c'était très bien pardon, je t'ai dis des bêtises.

2024-12-21 22:48 UTC, xmanu91 commented on ui/Button.py
> +    def __init__(self, default_color,hover_color, width, height, x, y, image, action):
Il ne faut pas oublier aussi le texte à afficher dans le bouton (par exemple "Jouer", "Paramètres", ...)

2024-12-21 22:48 UTC, xmanu91 commented on ui/Button.py
> +
Pas besoin de mettre autant de commentaire ne t'en fait pas. Met juste des commentaire quand il y a possibilité de ne pas comprendre. Normalement si ton code est bien fait il se comprend facilement. Ton code est bien fait ! Donc tu n'as autant besoins de commentaires...

2024-12-22 12:34 UTC, malo-0 commented on ui/Button.py
> +
j'en ai quand meme mis quelques un dans la création, ça m'a permis de pas trop m'emmêler les pinceaux !  
Y'en a quand meme un peu mais bon !

2024-12-22 13:36 UTC, xmanu91 commented on ui/Button.py
> +    def __init__(self, default_color, hover_color, width, height, x, y, action, image, x_image, y_image, text, x_text, y_text):
Je me dis maintenant que pour faire un peu moins de paramètres à entrer, on pourait mettre les coordonnées et la taille dans un rect pygame nan ? Et les coordonées dans des tuples ?
```suggestion
    def __init__(self, default_color, hover_color, buttonRect, action, image, imageCoordinates, text, textCoordinates):
```

2024-12-22 13:39 UTC, xmanu91 requested changes
Voilà encore une petite modification pour raccourcir un peu le code et pour plus de simplicité mais sinon tout est nickel !

2024-12-22 19:16 UTC, xmanu91 approved these changes
Super travail Malo ! (J'ai juste rajouté le typage des paramètres mais je ne t'embête pas avec ça c'est un peu compliqué des fois

2024-12-22 19:16 UTC, merged